# Generated by Django 4.0 on 2024-04-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, default='defecto/defecto.png', null=True, upload_to='maquina/%Y/%m/%d')),
                ('marca', models.CharField(max_length=20)),
                ('segmento', models.CharField(max_length=20)),
                ('year', models.Field(blank=True, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=3)),
                ('pluma', models.CharField(blank=True, max_length=3)),
                ('plumin', models.CharField(blank=True, max_length=3)),
                ('potencia', models.CharField(blank=True, max_length=10)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
