# Generated by Django 4.0 on 2024-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruaspanama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='year',
        ),
        migrations.AddField(
            model_name='maquina',
            name='año',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='disponible',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='marca',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='segmento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
